name: xAxee-Plots
main: pl.xaxee.plots.PlotPlugin
version: 1.0
description: Plugin that adds regions management to players

depend:
  - WorldGuard
  - WorldEdit
commands:
  plot:
    description: Command that adds regions management
    aliases: [teren]